authors:
  negin513:
    name: Negin Sobhani
    description: HPC Consultant
    avatar: https://github.com/negin513.png
    slug: negin513
    url: https://github.com/negin513/

  benkirk:
    name: Ben Kirk
    description: NCAR CISL Consulting Services Group
    avatar: https://avatars.githubusercontent.com/u/2366572?v=4
    slug: benkirk
    url: https://github.com/benkirk/

  neumanbrett:
    name: Brett Neuman
    description: HPC Consultant
    avatar: https://github.com/neumanbrett.png
    slug: neumanbrett
    url: https://github.com/neumanbrett/

  matthews:
    name: Ben Matthews
    description: HPC Systems Engineer
    slug: matthews
    avatar: https://github.com/matthewsucar.png
    url: https://github.com/matthewsucar
  
  vanderwb:
    name: Brian Vanderwende
    description: HPC Consultant
    slug: vanderwb
    avatar: https://github.com/vanderwb.png
    url: https://github.com/vanderwb
